Repository FEMessage/vue-sfc-cli, pull requests merged in 2019-12, with the labels that each got.

#103 test: 增加 eslint-plugin-jest
  templates/.eslintrc.js
  templates/package-json
Labels: test

#105 chore: ci
  .travis.yml
  templates/.travis.yml
Labels: chore

#107 chore(deps): upgrade gren
  .grenrc.js
  init.js
  lib/fileActions.js
  package.json
  templates/.grenrc.js
  templates/_package.json
  yarn.lock
Labels: dependencies
