Repository FEMessage/vue-sfc-cli, pull requests merged in 2019-10, with the labels that each got.

#90 fix: `Vue.use` doesn't work
  templates/src/index.js
Labels: bug

#91 docs: update readme template
  templates/README.md
Labels: documentation

#92 chore(ci): 部署失败，不对github产生副作用
  templates/.travis.yml
  templates/build.sh
  templates/notify.sh
Labels: chore

#94 chore(ci): 钉钉通知时带上自身的版本号
  notify.sh
Labels: chore

#95 docs: change version badge service provider
  README-zh.md
  README.md
  templates/README.md
Labels: documentation

#96 chore: build with autoprefixer
  templates/build/rollup.config.js
Labels: chore

#97 docs: 补充通过命令创建的说明
  README-zh.md
  README.md
  init.js
Labels: documentation
