Repository FEMessage/vue-sfc-cli, pull requests merged in 2019-07, with the labels that each got.

#61 feat(template): 添加 jest
  .gitignore
  templates/.babelrc
  templates/.babelrc.js
  templates/package-json
  templates/test/index.test.js
  templates/test/sum.js
  templates/yarn.lock
Labels: enhancement

#63 chore(github): add `badge.yml`
  .github/badge.yml
  templates/.github/badge.yml
Labels: enhancement

#64 chore: 提取更新需更新的文件到配置文件
  README.md
  config/update-files.js
  lib/fileActions.js
Labels: chore

#71 chore(babel): remove absoluteRuntime option
  templates/.babelrc.js
Labels: chore

#72 chore: tweak styleguidist sidebar
  templates/gitignore
  templates/styleguide.config.js
Labels: chore

#73 chore: 当文档没有Guide时，styleguide侧边栏不显示Guide章节
  templates/styleguide.config.js
Labels: chore

#76 refactor: Use $(..) instead of legacy `..`.
  notify.sh
  templates/notify.sh
Labels: refactor

#77 perf: 减少多余的管道
  notify.sh
  templates/notify.sh
Labels: performance

#78 chore(deps): 固定 husky, prettier 版本
  config/update-files.js
  lib/fileActions.js
  templates/.stylelintrc
  templates/package-json
  templates/yarn.lock
Labels: dependencies

#79 chore: 配置完善
  templates/package-json
  templates/src/component.vue
Labels: chore

#74 chore: delete yarn.lock
  templates/yarn.lock
Labels: chore
